.snyk
app/config/index.js
app/data/models/application.js
app/messaging/fetch-application.js
app/messaging/fetch-claim.js
app/messaging/process-application.js
app/messaging/process-message.js
app/messaging/process-vet-visit.js
app/messaging/states.js
app/messaging/submit-claim.js
app/repositories/application-repository.js
changelog/db.changelog-1.3.xml
changelog/db.changelog.xml
package-lock.json
package.json
test/integration/narrow/app/messaging/process-application.test.js
test/unit/app/messaging/fetch-application.test.js
test/unit/app/messaging/fetch-claim.test.js
test/unit/app/messaging/process-message.test.js
test/unit/app/messaging/process-vet-visit.test.js
test/unit/app/messaging/submit-claim.test.js
test/unit/app/repository/application-repository.test.js

Mostly concerned with handling the claim submission. Also refactored message processing to use `sessionId` on message rather than in the body as this isn't required and prevents the sessionId from being saved to the db - which it currently it.

feat: add submit claim message processing

---

app/data/models/status.js
app/repositories/application-repository.js
changelog/db.changelog-1.6.xml
changelog/db.changelog.xml
package.json
test/unit/app/repository/application-repository.test.js

Review comment to tidy up application repository.

updated status to upper case. Split search application tests.

---

app/messaging/submit-claim.js
app/routes/api/applications.js
package-lock.json
package.json
test/integration/narrow/routes/api/applications.test.js

Reverts DEFRA/ffc-ahwr-application#35

Revert "Feature/application fraud check"

---

app/data/models/stage-configuration.js
app/data/models/stage-execution.js
app/repositories/stage-configuration-repository.js
app/repositories/stage-execution-repository.js
changelog/db.changelog-1.14.xml
changelog/db.changelog.xml
package.json
test/unit/app/repository/stage-configuration-repository.test.js
test/unit/app/repository/stage-execution-repository.test.js

https://dev.azure.com/defragovuk/DEFRA-FFC/_sprints/taskboard/DEFRA-FFC%20Vet%20Visits%20Team/DEFRA-FFC/Vet%20Visits/Sprint%2030?workitem=180416

FFC-180416: RBAC - Setup new database tables through Liquibase migration scripts

---

app/data/models/stage-configuration.js
app/data/models/stage-execution.js
app/repositories/stage-execution-repository.js
app/routes/api/stage-configuration.js
app/routes/api/stage-execution.js
app/server.js
changelog/db.changelog-1.15.xml
changelog/db.changelog.xml
docker-compose.migrate.yaml
package.json
test/integration/narrow/routes/api/stage-configuration.test.js
test/integration/narrow/routes/api/stage-execution.test.js
test/unit/app/repository/stage-execution-repository.test.js

https://dev.azure.com/defragovuk/DEFRA-FFC/_sprints/taskboard/DEFRA-FFC%20Vet%20Visits%20Team/DEFRA-FFC/Vet%20Visits/Sprint%2030?workitem=180420

FFC-180420 : Add new API Endpoints

---

.snyk
app/messaging/schema/submit-claim-schema.js
package-lock.json
package.json
test/unit/app/messaging/schema/submit-claim-schema.test.js

Adding number of animals tested property to claim

Adding number of animals tested property to claim

---

.snyk
app/config/index.js
app/messaging/schema/process-application-schema.js
package-lock.json
package.json
test/unit/app/messaging/application/process-application.test.js
test/unit/app/messaging/process-application-schema.test.js

Make some fields optional for endemics

Endemics Application 

---

app/messaging/application/submit-claim.js
package.json
test/unit/app/messaging/application/submit-claim.test.js

fix statuses on compliance check

fix statuses on compliance check

---

app/messaging/schema/process-application-schema.js
app/routes/api/claim.js
package.json
test/integration/narrow/routes/api/claim.test.js

App insights track exception on application / claim validation

Bugfix track exception on app validation

---

app/constants/claim.js
app/routes/api/claim.js
package.json
test/integration/narrow/routes/api/claim.test.js

334633 - claim submission validation

---

app/routes/api/claim.js
package.json
test/integration/narrow/routes/api/claim.test.js

validation bugs fixed

---

app/messaging/schema/submit-claim-schema.js
package.json

- [n/a] Updated README / confluence

Bugfix add org email claim schema

---

app/messaging/schema/process-application-schema.js
package.json

org-email bug fixed

---

app/messaging/schema/submit-claim-schema.js
package.json

remove space

---

app/constants/application-status.js
app/data/models/stage-execution.js
app/repositories/claim-repository.js
app/routes/api/claim.js
app/routes/api/stage-execution.js
changelog/db.changelog-1.27.xml
changelog/db.changelog-1.28.xml
changelog/db.changelog.xml
package.json
test/integration/narrow/routes/api/claim.test.js
test/integration/narrow/routes/api/stage-execution.test.js
test/unit/app/repository/claim-repository.test.js

315503 - Stage execution api updated to cover claim helper needs

---

app/lib/requires-compliance-check.js
app/messaging/application/submit-claim.js
app/repositories/claim-repository.js
app/routes/api/claim.js
package.json
sonar-project.properties
test/unit/app/lib/requires-compliance-check.test.js
test/unit/app/repository/claim-repository.test.js

344194 - All claims status will be in-check after submission

---

app/lib/send-email.js
app/messaging/application/process-application.js
package.json
test/unit/app/lib/send-email.test.js

Added userTypes  for new and existing Users
- [ X ] Removed all unnecessary console logs
- [ X ] Removed all commented out code
- [ n/a ] Updated README / confluence

changes for the email trigger

---

app/constants/claim.js
app/routes/api/claim.js
package.json

- [n/a] Updated README / confluence

bug 369042 - thresholds for number of animals tested

---

app/event-publisher/index.js
app/repositories/application-repository.js
app/repositories/claim-repository.js
package.json
test/unit/app/repository/claim-repository.test.js

337395 claim history

---

app/messaging/application/process-application.js
package.json

376086 fix emails sending

---

app/constants/claim.js
app/routes/api/claim.js
package.json
test/integration/narrow/routes/api/claim.test.js

366380 - Claim endpoint validation on BVD changes

---

app/repositories/claim-repository.js
package.json

370132 Bugfix add logging set claim

---

app/data/models/claim.js
app/repositories/claim-repository.js
package.json

Adding logging to the claim creation in the database
- [n/a] Updated README / confluence

370132 more logging to claim.create

---

app/data/models/claim.js
app/repositories/claim-repository.js
package.json

370132 more logging

---

app/data/models/claim.js
app/repositories/claim-repository.js
app/routes/api/claim.js
package.json
test/integration/narrow/routes/api/claim.test.js
test/unit/app/repository/claim-repository.test.js

316749 - URN number must be unique

---

app/data/models/claim.js
app/repositories/claim-repository.js
package.json

370132 more logging part 3

---

app/routes/api/claim.js
package.json

Use original data not from joi

---

app/data/models/claim.js
package.json

370132 default dates

---

app/lib/getAmount.js
app/routes/api/claim.js
package.json
test/data/claim-prices-config.json
test/unit/app/lib/getAmount.test.js

add review claims payment

---

app/messaging/application/process-application.js
package.json

391753 - User with NOT AGREED agreement can submit new agreement

---

app/routes/api/claim.js
package.json

adding try catch for sending email

---

app/lib/send-email.js
package.json

Amount in email fixed

---

app/lib/send-email.js
app/routes/api/claim.js
package.json

implementaation to Display app reference

---

app/lib/send-email.js
app/routes/api/claim.js
package.json

Email submission working fine

---

app/routes/api/claim.js
package.json

fix missing user email

---

app/lib/getAmount.js
package-lock.json
package.json

Logging payment

---

app/routes/api/claim.js
package.json

396185 - validation on number of pigs updated

---

app/repositories/application-repository.js
app/routes/api/contact-history.js
package.json

411214 (p1) history tab duplicate

---

app/lib/date-utils.js
app/repositories/application-repository.js
package.json
test/unit/app/lib/date-utils.test.js
test/unit/app/repository/application-repository.test.js

fix for search by date

---

app/repositories/claim-repository.js
app/routes/api/claim.js
package.json
test/integration/narrow/routes/api/claim.test.js
test/unit/app/repository/claim-repository.test.js

406943 & 408799 - Claims search functionality done

---

app/repositories/claim-repository.js
app/routes/api/claim.js
package.json
test/unit/app/repository/claim-repository.test.js

Claim search bug Fixed

---

app/repositories/claim-repository.js
package.json

status search bug fixed

---

app/lib/getAmount.js
app/routes/api/claim.js
package.json

409958 409976 404617 dairy follow up

---

app/repositories/claim-repository.js
package.json
test/unit/app/repository/claim-repository.test.js

Make unique URN check not case sensitive

---

helm/ffc-ahwr-application/templates/_container.yaml
package-lock.json
package.json

resolve sonar issues and audit

---

app/lib/getAmount.js
package-lock.json
package.json
test/unit/app/lib/getAmount.test.js

add PiHunt related rates and refactor getAmount

---

app/lib/getAmount.js
app/routes/api/claim.js
package.json
test/unit/app/lib/getAmount.test.js

add pi hunt flag

---

app/routes/api/claim.js
package.json
test/integration/narrow/routes/api/claim.test.js

Optional pi payments fix

---

app/routes/api/claim.js
package.json

Optional PI Hunt - all animals exception - positive review must have done all animals

---

app/routes/api/claim.js
package.json

Add logging to submit claim

---

app/lib/getAmount.js
app/routes/api/claim.js
package.json

Remove logging for submit claim

---

app/repositories/claim-repository.js
package.json

get data only for specific claim

---

app/routes/api/claim.js
package.json

Get payment data fix

---

app/repositories/application-repository.js
package.json
test/unit/app/repository/application-repository.test.js

445256 - History duplicate row bug fixed

---

README.md
package.json

Add a few notes about setting up Service Bus queues in Azure for local development.
- [n/a ] Removed all unnecessary console logs
- [n/a] Removed all commented out code

Add guidance to set up queues for local dev

---

app/messaging/schema/process-application-schema.js
package.json

449757 add logging to validation

---

app/lib/send-email.js
app/lib/sfd-client.js
app/messaging/application/process-application.js
app/messaging/schema/submit-sfd-schema.js
package.json
test/unit/app/lib/send-email.test.js
test/unit/app/lib/sfd-client.test.js

Logic in tests to handle boolean state of SFD message proxy feature flag

feat(AHWR-261): Only CC sent via SFD proxy route for Claim emails from ahwr-application

---

app/lib/getAmount.js
app/routes/api/stage-execution.js
package.json

Debugging on test environment to try and fix backoffice issue

Added console.log for stage executions endpoint

---

README.md
package-lock.json
package.json
test/scripts/README.md
test/scripts/lib/post.mjs
test/scripts/lib/reference.mjs
test/scripts/lib/sheep-tests.mjs
test/scripts/post-application.mjs
test/scripts/post-claim.mjs

Submit mock applications and claims to the API.
```sh
node test/scripts/post-application.mjs
```

test(NO-JIRA): mock application and claim scripts

---

app/config/message-queue.js
package.json

Added additional optional config for passing a connection string, for automation tests to use

AHWR-241: Added additional optional config for passing a connection string

---

app/repositories/claim.js
package-lock.json
package.json
test/integration/narrow/routes/api/claims.test.js

fix(AHWR-537): updated date for claim events

---

app/data/models/flag.js
app/repositories/flag-repository.js
app/routes/api/flags.js
changelog/db.changelog-1.32.xml
changelog/db.changelog.xml
package-lock.json
package.json
test/integration/narrow/routes/api/applications.flags.test.js

Also added new column to flag table for deletedNote.

(AHWR-722): Changed API for deleting flags to include a deletedNote

---

app/config/index.js
app/lib/requires-compliance-check.js
app/repositories/application-repository.js
app/routes/api/claim.js
helm/ffc-ahwr-application/templates/config-map.yaml
helm/ffc-ahwr-application/values.yaml
package.json
test/unit/app/lib/requires-compliance-check.test.js
test/unit/app/repository/application-repository.test.js

- remove old work implementation
- improve tests

AHWR-846: fix: requires compliance check tests, remove old work implementation
